name: Generate Snake

on:
  schedule:   # jalan otomatis tiap hari jam 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:   # bisa juga manual jalanin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake (SVG + GIF)
        uses: Platane/snk@v3
        with:
          github_user_name: Zakvsl
          outputs: |
            dist/snake.svg
            dist/snake.gif

      - name: Push to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # clone branch output kalau ada, kalau belum ada bikin baru
          git fetch origin output || true
          git checkout output || git checkout --orphan output

          # copy hasil build
          cp -r dist/* .

          git add .
          git commit -m "update snake" || echo "no changes to commit"

          # force push supaya gak bentrok
          git push origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
