name: Generate Snake

on:
  schedule:   # jalan otomatis tiap hari jam 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:  # bisa juga manual jalanin workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake (SVG + GIF)
        uses: Platane/snk@v3
        with:
          github_user_name: Zakvsl   # ganti dengan username lo
          outputs: |
            dist/snake.svg
            dist/snake.gif

      - name: Push snake files to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
